services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: taskman
      POSTGRES_PASSWORD: taskman_dev
      POSTGRES_DB: taskman
    ports:
      - "5432:5432"    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskman"]
      interval: 5s
      timeout: 5s
      retries: 5

  taskman:
    container_name: taskman_backend
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: Dockerfile.dev    
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://taskman:taskman_dev@postgres:5432/taskman_db
    volumes:
      - ./backend:/app